api_book_create:
  path:       /api/v1/items
  controller: App\Library\Infrastructure\Controller\BookController::create
  methods:    POST

api_book_list:
  path:       /api/v1/items
  controller: App\Library\Infrastructure\Controller\BookController::list
  methods:    GET

api_book_detail:
  path:       /api/v1/items/{uuid}
  controller: App\Library\Infrastructure\Controller\BookController::detail
  methods:    GET